"use client";

import { useRef, useState } from "react";

export type PosterGenerationProvider = "pollinations" | "pollinations-alt" | "huggingface" | "together";

type PosterGenerationStatus = "idle" | "loading" | "success" | "error";

type PosterGenerationEventData = {
  title: string;
  summary: string;
  lineup: string[];
  venueName: string;
  startsAt: string;
};

type PosterGenerationRoute = "editorial-jazz" | "club-digital" | "festival-solar" | "cinematic-prestige";

type GenerationParams = {
  eventData: PosterGenerationEventData;
  selectedRoute: PosterGenerationRoute;
  provider: PosterGenerationProvider;
};

type KeyedPosterGenerationProvider = Exclude<PosterGenerationProvider, "pollinations" | "pollinations-alt">;

type UsePosterGenerationResult = {
  status: PosterGenerationStatus;
  imageUrl: string | null;
  provider: PosterGenerationProvider;
  prompt: string;
  generate: (
    eventData: PosterGenerationEventData,
    selectedRoute: PosterGenerationRoute,
    provider: PosterGenerationProvider,
  ) => Promise<void>;
  regenerate: () => void;
  reset: () => void;
};

const styleMap: Record<PosterGenerationRoute, string> = {
  "editorial-jazz":
    "sophisticated editorial poster, typographic tension, dark organic forms, nocturnal cultural premium feel, elegant layout",
  "club-digital":
    "high contrast neon accents, kinetic club energy, dark digital controlled light, after-party atmosphere, bold hierarchy",
  "festival-solar":
    "warm celebratory festival poster, wide layered composition, strong lineup presence, open memorable atmosphere",
  "cinematic-prestige":
    "cinematic drama, film grain texture, directed moody lighting, depth and shadow, unrepeatable prestige visual event",
};

function formatEventDate(dateValue: string) {
  return new Intl.DateTimeFormat("es-MX", {
    dateStyle: "full",
    timeStyle: "short",
  }).format(new Date(dateValue));
}

function buildPrompt(eventData: PosterGenerationEventData, selectedRoute: PosterGenerationRoute) {
  return `Professional event poster. Event: ${eventData.title}. ${eventData.summary}. Lineup: ${eventData.lineup.join(", ")}. Venue: ${eventData.venueName}. Date: ${formatEventDate(eventData.startsAt)}. Visual style: ${styleMap[selectedRoute]}. Dark background, bold display typography, high-end music event aesthetic, high production value. No text overlays generated by the model. Vertical format.`;
}

function delay(ms: number) {
  return new Promise((resolve) => {
    window.setTimeout(resolve, ms);
  });
}

async function waitForImageToLoad(url: string) {
  return new Promise<string>((resolve, reject) => {
    const image = new window.Image();
    image.decoding = "async";
    image.referrerPolicy = "no-referrer";

    const cleanup = () => {
      image.onload = null;
      image.onerror = null;
    };

    image.onload = () => {
      cleanup();
      resolve(url);
    };

    image.onerror = () => {
      cleanup();
      reject(new Error("No se pudo cargar la imagen generada."));
    };

    image.src = url;
  });
}

async function blobToDataUrl(blob: Blob) {
  return new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      if (typeof reader.result === "string") {
        resolve(reader.result);
        return;
      }

      reject(new Error("No se pudo convertir la imagen."));
    };
    reader.onerror = () => reject(new Error("No se pudo leer la imagen."));
    reader.readAsDataURL(blob);
  });
}

function buildProviderPrompt(prompt: string, provider: PosterGenerationProvider) {
  if (provider === "pollinations-alt") {
    return `${prompt} Premium collectible poster, cinematic lighting, sharper silhouette, richer contrast, tactile paper feel, daring composition, no blur haze, no muddy blacks.`;
  }

  return prompt;
}

async function generatePollinations(prompt: string, provider: Extract<PosterGenerationProvider, "pollinations" | "pollinations-alt">) {
  const url = `https://image.pollinations.ai/prompt/${encodeURIComponent(buildProviderPrompt(prompt, provider))}?width=1080&height=1920&nologo=true&seed=${Date.now()}`;
  return url;
}

async function generateHuggingFace(prompt: string, apiKey: string) {
  const response = await fetch("https://api-inference.huggingface.co/models/black-forest-labs/FLUX.1-schnell", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ inputs: prompt }),
  });

  if (!response.ok) {
    throw new Error("HF failed");
  }

  return blobToDataUrl(await response.blob());
}

async function generateTogether(prompt: string, apiKey: string) {
  const response = await fetch("https://api.together.xyz/v1/images/generations", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${apiKey}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      model: "black-forest-labs/FLUX.1-schnell-Free",
      prompt,
      width: 1080,
      height: 1920,
      n: 1,
    }),
  });

  if (!response.ok) {
    throw new Error("Together failed");
  }

  const payload = (await response.json()) as { data?: Array<{ url?: string }> };
  const url = payload.data?.[0]?.url;

  if (!url) {
    throw new Error("Together failed");
  }

  return url;
}

export function usePosterGeneration(
  getProviderKey: (provider: KeyedPosterGenerationProvider) => string,
): UsePosterGenerationResult {
  const [status, setStatus] = useState<PosterGenerationStatus>("idle");
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [provider, setProvider] = useState<PosterGenerationProvider>("pollinations");
  const [prompt, setPrompt] = useState("");
  const paramsRef = useRef<GenerationParams | null>(null);

  async function runGeneration(params: GenerationParams, attempt = 0): Promise<void> {
    const nextPrompt = buildPrompt(params.eventData, params.selectedRoute);
    paramsRef.current = params;
    setProvider(params.provider);
    setPrompt(nextPrompt);
    setStatus("loading");

    try {
      let nextUrl = "";

      if (params.provider === "pollinations" || params.provider === "pollinations-alt") {
        nextUrl = await generatePollinations(nextPrompt, params.provider);
      } else if (params.provider === "huggingface") {
        nextUrl = await generateHuggingFace(nextPrompt, getProviderKey("huggingface"));
      } else {
        nextUrl = await generateTogether(nextPrompt, getProviderKey("together"));
      }

      await waitForImageToLoad(nextUrl);
      setImageUrl(nextUrl);
      setStatus("success");
    } catch {
      if (attempt === 0) {
        await delay(1500);
        return runGeneration(params, 1);
      }

      setImageUrl(null);
      setStatus("error");
    }
  }

  async function generate(
    eventData: PosterGenerationEventData,
    selectedRoute: PosterGenerationRoute,
    nextProvider: PosterGenerationProvider,
  ) {
    await runGeneration({ eventData, selectedRoute, provider: nextProvider });
  }

  function regenerate() {
    if (!paramsRef.current) {
      return;
    }

    void runGeneration(paramsRef.current);
  }

  function reset() {
    setStatus("idle");
    setImageUrl(null);
    setPrompt("");
    paramsRef.current = null;
  }

  return {
    status,
    imageUrl,
    provider,
    prompt,
    generate,
    regenerate,
    reset,
  };
}
